Django_app/Menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

Django_app/Menu/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
	name = models.CharField(max_length=20)
	phone_number = models.CharField(max_length=15)
	address = models.CharField(max_length=50, blank=True)

	def __str__(self):
		return self.name

class Food(models.Model):
	name = models.CharField(max_length=20)
	price = models.DecimalField(max_digits=3, decimal_places=0)
	comment = models.CharField(max_length=50, blank=True)
	is_spicy = models.BooleanField(default=False)
	restaurant = models.ForeignKey(Restaurant)

	def __str__(self):
		return self.name

Django_app/Menu/views.py
from django.shortcuts import render_to_response
# Create your views here.
from .models import Restaurant, Food

def index(request):
	restaurants = Restaurant.objects.all()
	return render_to_response('cms/menu.html',locals())

Django_app/Menu/templates/cms/menu.html
<!DOCTYPE html>
<html lang="">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Title Page</title>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<h1 class="text-center">美食菜單</h1>
		<div class="container-fluid">
		{% for r in restaurants %}
		<h2>{{ r.name }}</h2>
		{% if r.food_set.all %}
		<p>本餐廳共有{{ r.food_set.all|length }}道菜</p>
		<table class="table">
			<tr>
				<th>菜名</th>
				<th>價格</th>
				<th>辣不辣</th>
				<th>註解</th>
			</tr>
			{% for food in r.food_set.all %}
			<tr>
				<td>{{ food.name }}</td>
				<td>{{ food.price }}</td>
				<td>{% if food.is_spicy %} 辣 {% else %} 不辣 {% endif %}</td>
				<td>{{ food.comment }}</td>
			</tr>
			{% endfor %}
		</table>
			{% else %}
			<p>本餐廳啥都沒賣</p>
			{% endif %}
			{% endfor %}



	</div>
		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
 		<script src="Hello World"></script>
	</body>
</html>